### ISSUE TITLE
*invalid* in mode-line

### ISSUE THREAD

**Issue by wdenton** [ecraven/celestial-mode-line#2]
I have this in my init.el, but when I start I end up with "*invalid*" in my mode-line:

    (require 'celestial-mode-line)
    (setq calendar-longitude -79.4)
    (setq calendar-latitude 43.7)
    (setq calendar-location-name "Toronto")
    (push 'celestial-mode-line-string global-mode-string)
    (celestial-mode-line-start-timer)

If I C-x C-e the "push" line then things work and "*invalid*" is replaced with the proper stuff. Switching the last two lines doesn't help. Should this not work as is? 

Great package! I'm really happy to have this. Thanks for all your work!

**Comment by ecraven** [comment]
Sorry about this, the =push= from README is actually incorrect. I've fixed the README, the correct code is:
````
;; add to end of global-mode-string
(add-to-list 'global-mode-string 'celestial-mode-line-string t)
````
Can you try this? It should actually work ;)

**Comment by wdenton** [comment]
That makes `*invalid*` all that ever shows, not matter what I execute! Here's what I have now:

````
(require 'celestial-mode-line)
(setq calendar-longitude -79.4)
(setq calendar-latitude 43.7)
(setq calendar-location-name "Toronto")
(add-to-list 'global-mode-string 'celestial-mode-line-string t)
(celestial-mode-line-start-timer)
````

Tried it with `emacs -Q` and had the same result. There's a flash where the information appears in the minibuffer, but it never makes it into the mode-line.

**Comment by ecraven** [comment]
Can you tell me which emacs version you are using exactly? M-x version
Also, are you using powerline or any other customized mode-line?

**Comment by wdenton** [comment]
My apologies for not including that from the start. I'm compiling Emacs from source:

GNU Emacs 27.0.50 (build 7, x86_64-pc-linux-gnu, GTK+ Version 3.22.25) of 2017-12-07

I am using powerline too, with just `(powerline-default-theme)` to set it up. (When I ran with -Q and no powerline, I did still get that `*invalid*` message.)

In case it helps:

````
global-mode-string is a variable defined in ‘C source code’.
Its value is (celestial-mode-line-string)
````

I ran (celestial-mode-line-update) and caught this in `*Messages*`:

````
#(" 3☾ ☀↓16:38" 0 11 (help-echo "Last Quarter Moon in 3 days on Sunday, December 10, 2017 at 2:57am (EST)"))
````

I thought that, or a similar command, might force the mode-line to update, but nothing I tried did. I'm glad to try more, or whatever else might help.

**Comment by ecraven** [comment]
hm.. that might be it, global-mode-string should be '("" celestial-mode-line-string) (note the "" at the beginning).
It seems I have some module that already sets it. Could you try 
````
(setq global-mode-string '("" celestial-mode-line-string))
````
and tell me whether that fixes it? if it does, I'll update the plugin accordingly.

Thanks for the detailed descriptions!

**Comment by seanhagen** [comment]
I swapped my latitude & longitude ( realised they were wrong ), and tried a few things. 

The config is now just this:

```
(use-package celestial-mode-line
  :ensure t
  :config
  (setq calendar-longitude -122.984
        calendar-latitude 49.280
        calendar-location-name "Burnaby, BC"
        global-mode-string '(""))
  (add-to-list 'global-mode-string 'celestial-mode-line-string t)
  (celestial-mode-line-start-timer))
```

And that works!
![screenshot from 2017-12-07 14-40-15](https://user-images.githubusercontent.com/444767/33742312-abec24f4-db5c-11e7-992c-bca07898ba2d.png)

Thanks for your help :smile:

**Comment by wdenton** [comment]
This works for me too! Thanks for celestial-mode-line, and thanks for the use-package example.

M-x all-praise-emacs!

**Comment by ecraven** [comment]
Perfect! Just keep in mind that other packages might modify `global-mode-string` too, so be sure to add them *after* this. I will update the Readme later. Thanks for the help in finding the problem!
